COMP: Move required include's to the top of the file
To address:

’ does not name a template type
   using ToDream3DType = itk::InPlaceImageToDream3DDataFilter<PixelType, Dimension>;
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/matt/src/DREAM3D/Source/Plugins/MultiscaleFusion/MultiscaleFusionFilters/ITKMontageFromFilesystem.cpp:518:12: error: ‘ToDream3DType’ has not been declared
   typename ToDream3DType::Pointer toDream3DFilter = ToDream3DType::New();
            ^~~~~~~~~~~~~
/home/matt/src/DREAM3D/Source/Plugins/MultiscaleFusion/MultiscaleFusionFilters/ITKMontageFromFilesystem.cpp:518:35: error: expected ‘(’ before ‘toDream3DFilter’
   typename ToDream3DType::Pointer toDream3DFilter = ToDream3DType::New();
                                   ^~~~~~~~~~~~~~~
/home/matt/src/DREAM3D/Source/Plugins/MultiscaleFusion/MultiscaleFusionFilters/ITKMontageFromFilesystem.cpp:519:3: error: ‘toDream3DFilter’ was not declared in this scope
   toDream3DFilter->SetInput(streamingFilter->GetOutput());
   ^~~~~~~~~~~~~~~
/home/matt/src/DREAM3D/Source/Plugins/MultiscaleFusion/MultiscaleFusionFilters/ITKMontageFromFilesystem.cpp:519:3: note: suggested alternative: ‘streamingFilter’
   toDream3DFilter->SetInput(streamingFilter->GetOutput());
   ^~~~~~~~~~~~~~~
   streamingFilter

/home/matt/src/DREAM3D/Source/Plugins/MultiscaleFusion/MultiscaleFusionFilters/ITKMontageFromFilesystem.cpp:604:0: warning: "ITK_IMAGE_READER_CLASS_NAME" redefined
 #define ITK_IMAGE_READER_CLASS_NAME ITKMontageFromFilesystem

/home/matt/src/SIMPL/Source/SIMPLib/ITK/itkImageReaderHelper.cpp:10:0: note: this is the location of the previous definition
 #define ITK_IMAGE_READER_CLASS_NAME Foo